spring.application.name=back-end
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=KingStep_shop;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngovandat10a5@gmail.com
spring.mail.password=ulxq jsah ntet vblv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=*
ghn.token=55bb4252-5665-11f0-9b81-222185cb68c8
ghn.shopId=196987
ghn.baseUrl=https://dev-online-gateway.ghn.vn/shiip/public-api

# C?u hnh VNPay
vnp_TmnCode=1YQ80PHL
vnp_HashSecret=17NNGXL3FCWJ06G5XFAVNE27J8PYF2KR
vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnUrl=http://localhost:3000/check-payment
vnp_apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction